### ISSUE TITLE
为什么单核和双核下的运行时间没有显著差异呢

### ISSUE THREAD

**Issue by ArchFeh** [godka/simpleMdMpi#1]

**Comment by godka** [comment]
您好~
但是这个年代也太久远了。。
当年差异挺显著的，我尽量找找看看我这边有没有可执行文件你试试

**Comment by godka** [comment]
我没查阅到源代码，但是找到了当时的实验报告。
似乎你说的对，单核和双核并没有显著差异，详细报告如下：

N = 640时：

核心 | 耗时(s)
-- | --
1 | 17.0847
2 | 17.0847
3 | 8.93966
4 | 5.94734
5 | 4.74042
6 | 3.78677
7 | 3.45085
8 | 3.03387
9 | 2.93504
10 | 3.07984
11 | 2.41174
12 | 2.71981
13 | 2.82167
14 | 2.72238
15 | 2.49414
16 | 2.3678
17 | 2.40279
18 | 2.36357
19 | 2.43848
20 | 2.24086
21 | 2.23121
22 | 2.72183
23 | 2.95458
24 | 3.14899

N = 6400时：

核心 | 耗时(s)
-- | --
1 | 1677.32
2 | 1675.71
3 | 867.197
4 | 593.611
5 | 448.936
6 | 362.28
7 | 303.25
8 | 265.328
9 | 231.841
10 | 208.535
11 | 194.421
12 | 182.444
13 | 206.11
14 | 201.676
15 | 195.583
16 | 187.362
17 | 179.829
18 | 172.686
19 | 166.072
20 | 159.806
21 | 154.195
22 | 151.594
23 | 141.216
24 | 136.849

此外，当年的报告中我给出了一定解释：

> 从实验结果中可以看出，在粒子数较小的情况下，并行优势并没有完全发挥出，甚至出现24核的耗时会低于21核耗时，因为在并行计算的耗时远远小于分配数据给核心的耗时。而在粒子数较大的情况下，并行的优势得到了体现。 如图N = 6400所示，加速比与N = 640相比有了非常明显的提升。
由于本次实验机器是12核心24线程，故在核心数大于12后由于超线程模拟核心导致效率略下降，随后缓步爬升，但是模拟核心加速比远不如原生12核心。

我现在已经太菜了，不知道当时写得对不对了，希望能够给到你一定参考~

**Comment by ArchFeh** [comment]
谢谢你的回答和代码。我也赞同你的解释！
